<?php

declare(strict_types=1);

namespace Saiman\SaimanCrud\Commands;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

final class RevertCrudCommand extends Command
{
    protected $signature = 'crud:revert
                            {model : The model name to revert (e.g. Product, BlogPost)}
                            {--api : Also revert API-specific files}
                            {--with-layout : Also delete the generated layout file}
                            {--keep-table : Keep the database table (only delete files)}
                            {--dry-run : Show what would be deleted without actually deleting}';

    protected $description = 'Revert (delete) all files generated by make:crud for a given model';

    private Filesystem $files;

    /**
     * @var array<int, string>
     */
    private array $deleted = [];

    /**
     * @var array<int, string>
     */
    private array $routesRemoved = [];

    private bool $tableDropped = false;

    public function handle(): int
    {
        $this->files = new Filesystem;

        $rawModel = (string) $this->argument('model');

        if (! $this->isValidModelName($rawModel)) {
            $this->components->error(
                "Invalid model name [{$rawModel}]. Must start with uppercase (e.g. Product, BlogPost)."
            );

            return self::FAILURE;
        }

        $modelName  = Str::studly($rawModel);
        $isDryRun   = (bool) $this->option('dry-run');
        $isApi      = (bool) $this->option('api');
        $withLayout = (bool) $this->option('with-layout');
        $keepTable  = (bool) $this->option('keep-table');
        $tableName  = Str::snake(Str::plural($modelName));

        $this->newLine();
        $this->line('  <fg=cyan;options=bold>Laravel Saiman CRUD Revert</>');
        $this->line('  ──────────────────────────────────────────');
        $this->components->twoColumnDetail('  Model', $modelName);
        $this->components->twoColumnDetail('  Table', $tableName);
        $this->components->twoColumnDetail('  Mode', $isDryRun ? 'Dry Run (no changes)' : 'Live');

        if ($keepTable) {
            $this->components->twoColumnDetail('  Keep Table', 'Yes (table will NOT be dropped)');
        }

        $this->line('  ──────────────────────────────────────────');
        $this->newLine();

        $filesToDelete = $this->collectFiles($modelName, $isApi);
        $existingFiles = $this->getExistingFiles($filesToDelete, $modelName, $isApi, $withLayout, $keepTable, $tableName);

        if (empty($existingFiles)) {
            $this->components->info("No CRUD files found for [{$modelName}]. Nothing to revert.");

            return self::SUCCESS;
        }

        $this->components->warn('The following will be affected:');
        $this->newLine();

        foreach ($existingFiles as $file) {
            $this->line("    <fg=red>✗</> {$file}");
        }

        $this->newLine();

        if ($isDryRun) {
            $this->components->info('Dry run mode — no changes were made.');
            $this->newLine();
            $this->line('  Run without <fg=yellow>--dry-run</> to actually delete:');
            $this->line("    <fg=yellow>php artisan crud:revert {$modelName}</>");
            $this->newLine();

            return self::SUCCESS;
        }

        if (! $this->components->confirm("Are you sure you want to revert all CRUD for [{$modelName}]?", false)) {
            $this->components->info('Cancelled. No changes were made.');

            return self::SUCCESS;
        }

        if (! $this->components->confirm('This action cannot be undone. Continue?', false)) {
            $this->components->info('Cancelled. No changes were made.');

            return self::SUCCESS;
        }

        // Step 1: Drop table from database (before deleting migration file)
        if (! $keepTable) {
            $this->dropTable($tableName);
        }

        // Step 2: Remove migration record from migrations table
        if (! $keepTable) {
            $this->removeMigrationRecord($tableName);
        }

        // Step 3: Delete all generated files
        foreach ($filesToDelete as $label => $path) {
            $this->deleteFile($label, $path);
        }

        // Step 4: Delete view directories
        $viewFolder = Str::snake(Str::plural($modelName));
        $this->deleteDirectory('Views directory', resource_path("views/{$viewFolder}"));
        $this->deleteDirectory('Livewire views', resource_path("views/livewire/{$viewFolder}"));

        // Step 5: Delete migration files
        $this->deleteMigrationFiles($modelName);

        // Step 6: Remove routes
        $this->removeRoutes($modelName, 'web');
        if ($isApi) {
            $this->removeRoutes($modelName, 'api');
        }

        // Step 7: Delete layout if requested
        if ($withLayout) {
            $this->deleteFile('Layout', resource_path('views/layouts/app.blade.php'));
        }

        $this->printSummary($tableName, $keepTable);

        return self::SUCCESS;
    }

    /**
     * Drop the database table if it exists.
     */
    private function dropTable(string $tableName): void
    {
        try {
            if (Schema::hasTable($tableName)) {
                Schema::dropIfExists($tableName);
                $this->tableDropped = true;

                $this->components->twoColumnDetail(
                    '  <fg=red>✗</> Database table',
                    "<fg=gray>Dropped table [{$tableName}]</>"
                );
            }
        } catch (\Exception $e) {
            $this->components->warn("  Could not drop table [{$tableName}]: {$e->getMessage()}");
        }
    }

    /**
     * Remove the migration record from the migrations table so it won't show as "already ran".
     */
    private function removeMigrationRecord(string $tableName): void
    {
        try {
            if (Schema::hasTable('migrations')) {
                $migrationName = "create_{$tableName}_table";

                $deleted = DB::table('migrations')
                    ->where('migration', 'like', "%{$migrationName}%")
                    ->delete();

                if ($deleted > 0) {
                    $this->components->twoColumnDetail(
                        '  <fg=red>✗</> Migration record',
                        '<fg=gray>Removed from migrations table</>'
                    );
                }
            }
        } catch (\Exception $e) {
            $this->components->warn("  Could not clean migration record: {$e->getMessage()}");
        }
    }

    /**
     * @return array<string, string>
     */
    private function collectFiles(string $modelName, bool $isApi): array
    {
        $files = [];

        $files['Model']                = app_path("Models/{$modelName}.php");
        $files['Controller']           = app_path("Http/Controllers/{$modelName}Controller.php");
        $files['Store Request']        = app_path("Http/Requests/Store{$modelName}Request.php");
        $files['Update Request']       = app_path("Http/Requests/Update{$modelName}Request.php");
        $files['Seeder']               = database_path("seeders/{$modelName}Seeder.php");
        $files['Factory']              = database_path("factories/{$modelName}Factory.php");
        $files['Service']              = app_path("Services/{$modelName}Service.php");
        $files['Repository Interface'] = app_path("Repositories/{$modelName}RepositoryInterface.php");
        $files['Repository']           = app_path("Repositories/{$modelName}Repository.php");
        $files['Livewire Component']   = app_path("Livewire/{$modelName}Manager.php");
        $files['Filament Resource']    = app_path("Filament/Resources/{$modelName}Resource.php");

        if ($isApi) {
            $files['API Controller'] = app_path("Http/Controllers/Api/{$modelName}Controller.php");
            $files['API Resource']   = app_path("Http/Resources/{$modelName}Resource.php");
        }

        return $files;
    }

    /**
     * @param  array<string, string>  $filesToDelete
     * @return array<int, string>
     */
    private function getExistingFiles(
        array $filesToDelete,
        string $modelName,
        bool $isApi,
        bool $withLayout,
        bool $keepTable,
        string $tableName,
    ): array {
        $existing = [];

        // Check if database table exists
        if (! $keepTable) {
            try {
                if (Schema::hasTable($tableName)) {
                    $existing[] = "DATABASE TABLE: {$tableName} (will be dropped)";
                }
            } catch (\Exception) {
                // Database not available — skip table check
            }
        }

        foreach ($filesToDelete as $path) {
            if ($this->files->exists($path)) {
                $existing[] = str_replace(base_path().DIRECTORY_SEPARATOR, '', $path);
            }
        }

        $viewFolder = Str::snake(Str::plural($modelName));

        $viewDir = resource_path("views/{$viewFolder}");
        if ($this->files->isDirectory($viewDir)) {
            $existing[] = str_replace(base_path().DIRECTORY_SEPARATOR, '', $viewDir).'/';
        }

        $livewireDir = resource_path("views/livewire/{$viewFolder}");
        if ($this->files->isDirectory($livewireDir)) {
            $existing[] = str_replace(base_path().DIRECTORY_SEPARATOR, '', $livewireDir).'/';
        }

        $migrationTable = Str::snake(Str::plural($modelName));
        $migrations     = $this->files->glob(database_path("migrations/*_create_{$migrationTable}_table.php"));
        foreach ($migrations as $migration) {
            $existing[] = str_replace(base_path().DIRECTORY_SEPARATOR, '', $migration);
        }

        $routeMarker = '// CRUD-GENERATED:START '.$modelName;

        $routePath = base_path('routes/web.php');
        if ($this->files->exists($routePath) && str_contains($this->files->get($routePath), $routeMarker)) {
            $existing[] = 'routes/web.php (generated route block)';
        }

        if ($isApi) {
            $apiPath = base_path('routes/api.php');
            if ($this->files->exists($apiPath) && str_contains($this->files->get($apiPath), $routeMarker)) {
                $existing[] = 'routes/api.php (generated route block)';
            }
        }

        if ($withLayout) {
            $layoutPath = resource_path('views/layouts/app.blade.php');
            if ($this->files->exists($layoutPath)) {
                $existing[] = 'resources/views/layouts/app.blade.php';
            }
        }

        return $existing;
    }

    private function deleteFile(string $label, string $path): void
    {
        if (! $this->files->exists($path)) {
            return;
        }

        $display = str_replace(base_path().DIRECTORY_SEPARATOR, '', $path);

        $this->files->delete($path);
        $this->deleted[] = $display;

        $this->components->twoColumnDetail(
            "  <fg=red>✗</> {$label}",
            "<fg=gray>{$display}</>"
        );
    }

    private function deleteDirectory(string $label, string $path): void
    {
        if (! $this->files->isDirectory($path)) {
            return;
        }

        $display = str_replace(base_path().DIRECTORY_SEPARATOR, '', $path);

        $this->files->deleteDirectory($path);
        $this->deleted[] = $display.'/';

        $this->components->twoColumnDetail(
            "  <fg=red>✗</> {$label}",
            "<fg=gray>{$display}/</>"
        );
    }

    private function deleteMigrationFiles(string $modelName): void
    {
        $tableName  = Str::snake(Str::plural($modelName));
        $migrations = $this->files->glob(database_path("migrations/*_create_{$tableName}_table.php"));

        foreach ($migrations as $migration) {
            $display = str_replace(base_path().DIRECTORY_SEPARATOR, '', $migration);

            $this->files->delete($migration);
            $this->deleted[] = $display;

            $this->components->twoColumnDetail(
                '  <fg=red>✗</> Migration file',
                "<fg=gray>{$display}</>"
            );
        }
    }

    private function removeRoutes(string $modelName, string $type): void
    {
        $routeFile = $type === 'api' ? 'api.php' : 'web.php';
        $routePath = base_path("routes/{$routeFile}");

        if (! $this->files->exists($routePath)) {
            return;
        }

        $content      = $this->files->get($routePath);
        $escapedModel = preg_quote($modelName, '/');

        $pattern = "/\n?\\/\\/ CRUD-GENERATED:START {$escapedModel}\n.*?\\/\\/ CRUD-GENERATED:END {$escapedModel}\n?/s";

        if (! preg_match($pattern, $content)) {
            return;
        }

        $content = (string) preg_replace($pattern, "\n", $content);
        $content = (string) preg_replace("/\n{3,}/", "\n\n", $content);
        $content = rtrim($content)."\n";

        $this->files->put($routePath, $content);
        $this->routesRemoved[] = $routeFile;

        $this->components->twoColumnDetail(
            "  <fg=red>✗</> Routes ({$routeFile})",
            "<fg=gray>Removed generated {$modelName} route block</>"
        );
    }

    private function printSummary(string $tableName, bool $keepTable): void
    {
        $this->newLine();
        $this->line('  ──────────────────────────────────────────');

        $parts   = [];
        $parts[] = count($this->deleted).' file(s) deleted';
        $parts[] = count($this->routesRemoved).' route file(s) cleaned';

        if ($this->tableDropped) {
            $parts[] = "table [{$tableName}] dropped";
        } elseif ($keepTable) {
            $parts[] = "table [{$tableName}] kept (use --keep-table)";
        }

        $this->components->info('Reverted! '.implode(', ', $parts).'.');

        $this->newLine();
    }

    private function isValidModelName(string $name): bool
    {
        return $name !== '' && (bool) preg_match('/^[A-Z][A-Za-z0-9]+$/', $name);
    }
}
